apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nextcloud-cert
  namespace: external-resources
  annotations:
    avp.kubernetes.io/path: "argocd/data/argocd-vault-plugin/nextcloud"
spec:
  secretName: nextcloud-cert
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  issuerRef:
    name: nextcloud-letsencrypt
    kind: Issuer
  commonName: <path:argocd/data/argocd-vault-plugin/nextcloud#nextcloud-url> # nextcloud-url
  dnsNames:
    - <path:argocd/data/argocd-vault-plugin/nextcloud#nextcloud-url> # nextcloud-url
---
#Wildcard
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: external-resources
  annotations:
    avp.kubernetes.io/path: "argocd/data/argocd-vault-plugin/nextcloud"
spec:
  secretName: diagon-ally-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  issuerRef:
    name: vault-issuer
    kind: Issuer
  commonName: "*.diagon.ally"
  dnsNames:
  - "*.diagon.ally"
  - "diagon.ally"